spring:
  profiles:
#    active: dev
    active: prod
    include: s3, security, docs, openai

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework: INFO

firebase:
  config-path: src/main/resources/firebase-service-key.json
